### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by Mehran** [bhattsameer/SMS-and-Email-BOMBER#3]
```
Traceback (most recent call last):
  File "SMS_bomber_version2.py", line 54, in <module>
    send(input("Enter Target Number : "), int(input("Enter Number of Messages : ")), 1)
ValueError: invalid literal for int() with base 10: 'test'
```

**Comment by bhattsameer** [comment]
Hi There, 
This error was occurred because you Enter string value in the field where the input is assumed as Integer value. 
so the solution is..
just re run this program.
in first option it will ask Enter the target mobile number: (just enter mobile number here)
in second option it will ask you to how any messages you want to send: (Enter Total NUMBER of messages you want to send in numerical value)

for example:

Enter the target mobile number: 1234567890
how many message you want to send: 5
